exports.message = Object.freeze({
    USERNAME_OR_PASSWORD_INCORRECT: 'USERNAME_OR_PASSWORD_INCORRECT',
    UNAUTHORIZED: 'UNAUTHORIZED',
    PERMISSION_DENIED: 'PERMISSION_DENIED'
});

exports.pagination = Object.freeze({
    SIZE_DEFAULT: 10
});

exports.ROLE_USER = "ROLE_USER";
exports.ROLE_ADMIN = "ROLE_ADMIN";

exports.DEFAULT_PASSWORD = "123456";